# Data Cleaning

In [1]:
#bibliotecas
import pandas as pd
from helpers import check_missing_values

pd.set_option('display.max_columns', None)

In [2]:
#dados
df_flights = pd.read_csv('../data/raw/flights.csv')
df_airlines = pd.read_csv('../data/raw/airlines.csv')
df_airports = pd.read_csv('../data/raw/airports.csv')

/tmp/ipykernel_69830/3470267361.py:2: DtypeWarning: Columns (0: ORIGIN_AIRPORT, 1: DESTINATION_AIRPORT) have mixed types. Specify dtype option on import or set low_memory=False.
  df_flights = pd.read_csv('../data/raw/flights.csv')

In [3]:
#cruzamento dos dados
df = df_flights.merge(
    df_airlines.rename(columns={'AIRLINE': 'AIRLINE_NAME'}), 
    left_on='AIRLINE', right_on='IATA_CODE', how='left'
).drop(columns=['IATA_CODE'])

df_airports = df_airports.rename(columns={'AIRPORT': 'AIRPORT_NAME'})

df = df.merge(
    df_airports.add_prefix('ORIGIN_'), 
    left_on='ORIGIN_AIRPORT', right_on='ORIGIN_IATA_CODE', how='left'
).drop(columns=['ORIGIN_IATA_CODE'])

df = df.merge(
    df_airports.add_prefix('DESTINATION_'),
    left_on='DESTINATION_AIRPORT', right_on='DESTINATION_IATA_CODE', how='left'
).drop(columns=['DESTINATION_IATA_CODE'])

df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE_NAME,ORIGIN_AIRPORT_NAME,ORIGIN_CITY,ORIGIN_STATE,ORIGIN_COUNTRY,ORIGIN_LATITUDE,ORIGIN_LONGITUDE,DESTINATION_AIRPORT_NAME,DESTINATION_CITY,DESTINATION_STATE,DESTINATION_COUNTRY,DESTINATION_LATITUDE,DESTINATION_LONGITUDE
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,-11.0,21.0,15.0,205.0,194.0,169.0,1448,404.0,4.0,430,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Alaska Airlines Inc.,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,-8.0,12.0,14.0,280.0,279.0,263.0,2330,737.0,4.0,750,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,American Airlines Inc.,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,Palm Beach International Airport,West Palm Beach,FL,USA,26.68316,-80.09559
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,18.0,-2.0,16.0,34.0,286.0,293.0,266.0,2296,800.0,11.0,806,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,US Airways Inc.,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,Charlotte Douglas International Airport,Charlotte,NC,USA,35.21401,-80.94313
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,-5.0,15.0,30.0,285.0,281.0,258.0,2342,748.0,8.0,805,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,American Airlines Inc.,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,Miami International Airport,Miami,FL,USA,25.79325,-80.29056
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,-1.0,11.0,35.0,235.0,215.0,199.0,1448,254.0,5.0,320,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Alaska Airlines Inc.,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 44 columns):
 #   Column                    Dtype
---  ------                    -----
 0   YEAR                      int64
 1   MONTH                     int64
 2   DAY                       int64
 3   DAY_OF_WEEK               int64
 4   AIRLINE                   str
 5   FLIGHT_NUMBER             int64
 6   TAIL_NUMBER               str
 7   ORIGIN_AIRPORT            object
 8   DESTINATION_AIRPORT       object
 9   SCHEDULED_DEPARTURE       int64
 10  DEPARTURE_TIME            float64
 11  DEPARTURE_DELAY           float64
 12  TAXI_OUT                  float64
 13  WHEELS_OFF                float64
 14  SCHEDULED_TIME            float64
 15  ELAPSED_TIME              float64
 16  AIR_TIME                  float64
 17  DISTANCE                  int64
 18  WHEELS_ON                 float64
 19  TAXI_IN                   float64
 20  SCHEDULED_ARRIVAL         int64
 21  ARRIVAL_TIME              float64
 22  ARRIVAL_DELAY             float64
 23  DIVERTED                  int64
 24  CANCELLED                 int64
 25  CANCELLATION_REASON       str
 26  AIR_SYSTEM_DELAY          float64
 27  SECURITY_DELAY            float64
 28  AIRLINE_DELAY             float64
 29  LATE_AIRCRAFT_DELAY       float64
 30  WEATHER_DELAY             float64
 31  AIRLINE_NAME              str
 32  ORIGIN_AIRPORT_NAME       str
 33  ORIGIN_CITY               str
 34  ORIGIN_STATE              str
 35  ORIGIN_COUNTRY            str
 36  ORIGIN_LATITUDE           float64
 37  ORIGIN_LONGITUDE          float64
 38  DESTINATION_AIRPORT_NAME  str
 39  DESTINATION_CITY          str
 40  DESTINATION_STATE         str
 41  DESTINATION_COUNTRY       str
 42  DESTINATION_LATITUDE      float64
 43  DESTINATION_LONGITUDE     float64
dtypes: float64(20), int64(10), object(2), str(12)
memory usage: 1.9+ GB

In [5]:
check_missing_values(df)

                        COLS  EMPTIES  EMPTIES (%)
25       CANCELLATION_REASON  5729195        98.46
26          AIR_SYSTEM_DELAY  4755640        81.72
30             WEATHER_DELAY  4755640        81.72
29       LATE_AIRCRAFT_DELAY  4755640        81.72
28             AIRLINE_DELAY  4755640        81.72
27            SECURITY_DELAY  4755640        81.72
36           ORIGIN_LATITUDE   490770         8.43
37          ORIGIN_LONGITUDE   490770         8.43
42      DESTINATION_LATITUDE   490775         8.43
43     DESTINATION_LONGITUDE   490775         8.43
32       ORIGIN_AIRPORT_NAME   486165         8.35
33               ORIGIN_CITY   486165         8.35
34              ORIGIN_STATE   486165         8.35
35            ORIGIN_COUNTRY   486165         8.35
39          DESTINATION_CITY   486165         8.35
38  DESTINATION_AIRPORT_NAME   486165         8.35
41       DESTINATION_COUNTRY   486165         8.35
40         DESTINATION_STATE   486165         8.35
15              ELAPSED_TIME   105071         1.81
22             ARRIVAL_DELAY   105071         1.81
16                  AIR_TIME   105071         1.81
18                 WHEELS_ON    92513         1.59
21              ARRIVAL_TIME    92513         1.59
19                   TAXI_IN    92513         1.59
13                WHEELS_OFF    89047         1.53
12                  TAXI_OUT    89047         1.53
11           DEPARTURE_DELAY    86153         1.48
10            DEPARTURE_TIME    86153         1.48
6                TAIL_NUMBER    14721         0.25
14            SCHEDULED_TIME        6         0.00

**Tratando nulos**

In [6]:
df_curated = df.copy()

In [7]:
#preenchendo campos nulos que ocorrem por não haver atraso
delay_cols = ['AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY']
df_curated[delay_cols] = df_curated[delay_cols].fillna(0)

#removendo motivo de cancelamento, praticamente vazia
df_curated = df_curated.drop(columns=['CANCELLATION_REASON'])

#removendo demais nulos
df_curated = df_curated.dropna(subset=[
    'ARRIVAL_DELAY',
    'ORIGIN_CITY', 
    'DESTINATION_CITY', 
    'ORIGIN_LATITUDE', 
    'DESTINATION_LATITUDE',
    'TAIL_NUMBER'
])

In [13]:
check_missing_values(df_curated)

Nenhum valor nulo encontrado no DataFrame.

**Filtrando dados**

In [9]:
#removendo voos cancelados e desviados, não ajudam na classificação
df_curated = df_curated[(df_curated['CANCELLED'] == 0) & (df_curated['DIVERTED'] == 0)]

**Obtendo target**

In [10]:
#criando a variável target
df_curated['IS_DELAYED'] = (df_curated['ARRIVAL_DELAY'] > 15).astype(int)

In [11]:
df_curated.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE_NAME,ORIGIN_AIRPORT_NAME,ORIGIN_CITY,ORIGIN_STATE,ORIGIN_COUNTRY,ORIGIN_LATITUDE,ORIGIN_LONGITUDE,DESTINATION_AIRPORT_NAME,DESTINATION_CITY,DESTINATION_STATE,DESTINATION_COUNTRY,DESTINATION_LATITUDE,DESTINATION_LONGITUDE,IS_DELAYED
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,-11.0,21.0,15.0,205.0,194.0,169.0,1448,404.0,4.0,430,408.0,-22.0,0,0,0.0,0.0,0.0,0.0,0.0,Alaska Airlines Inc.,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,0
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,-8.0,12.0,14.0,280.0,279.0,263.0,2330,737.0,4.0,750,741.0,-9.0,0,0,0.0,0.0,0.0,0.0,0.0,American Airlines Inc.,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,Palm Beach International Airport,West Palm Beach,FL,USA,26.68316,-80.09559,0
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,18.0,-2.0,16.0,34.0,286.0,293.0,266.0,2296,800.0,11.0,806,811.0,5.0,0,0,0.0,0.0,0.0,0.0,0.0,US Airways Inc.,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,Charlotte Douglas International Airport,Charlotte,NC,USA,35.21401,-80.94313,0
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,-5.0,15.0,30.0,285.0,281.0,258.0,2342,748.0,8.0,805,756.0,-9.0,0,0,0.0,0.0,0.0,0.0,0.0,American Airlines Inc.,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,Miami International Airport,Miami,FL,USA,25.79325,-80.29056,0
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,-1.0,11.0,35.0,235.0,215.0,199.0,1448,254.0,5.0,320,259.0,-21.0,0,0,0.0,0.0,0.0,0.0,0.0,Alaska Airlines Inc.,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,0

**Exportando dados**

In [12]:
df_curated.to_pickle('../data/curated/data.pkl')